### ISSUE TITLE
The last version return Oven and Oven Z1

### ISSUE THREAD

**Issue by MiguelAngelLV** [Andre0512/pyhOn#11]
Hi.

I am testing the last version and now, I don't know why, the last version return two devices: Oven a Oven Z1. With version of 14th works fine.

I think that Zone Support is the problem, but I don't know how solved.

The Z1 device return errors when HA try create some sensors (others works fine)

**Comment by Andre0512** [comment]
Hi, thanks for reporting! I have now disabled zones on devices with only one zone. I could imagine that in the future people will come with devices that need this, but we will see :slightly_smiling_face:
